version: "3.9"
services:
  database:
    image: postgres:14.1
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432"
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    restart: on-failure
    ports:
      - "8080:80"